# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'AutoInspector' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for AutoInspector

  target 'AutoInspectorTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'AutoInspectorUITests' do
    # Pods for testing
  end

	# add the Firebase pod for Google Analytics
	pod 'Firebase/Analytics'
	pod 'Firebase/Auth'
	pod 'Firebase/Core'
	pod 'Firebase/Firestore'
	pod 'Firebase/Database'

end
